### ISSUE TITLE
Expose typings

### ISSUE THREAD

**Issue by SimonJang** [Siderite/LInQer#12]
First of all, thanks for creating this library! I love the idea of 'lazy' generators when iterating.

Would it be possible to improve the typings? Intellisense in Typescript is non-existent at the moment. Since the API surface of this library is not trivial, it would be nice for developers to have decent intellisense when using your library.

**Comment by Siderite** [comment]
Thanks for the thanks :) !
You will have to be more precise. What do you mean by improve the typings? Can you give me an example?

**Comment by SimonJang** [comment]
I've make a small example in at [Stackblitz](https://stackblitz.com/edit/typescript-6wpy43) but there seems to be another issue not related to this issue.

![Screenshot from 2020-02-09 15-09-13](https://user-images.githubusercontent.com/10977475/74103649-2cd65e00-4b4e-11ea-8217-7120ed15e1b1.png)

For the typings, you do seem to have none (`*.d.ts`) included in your `package.json` `types` or `files` so when using LInQer with Typescript, it cannot infer any of the Typescript types that you are using, making the library a bit more difficult to use.

I can suggest [this medium article](https://itnext.io/step-by-step-building-and-publishing-an-npm-typescript-package-44fe7164964c). It explains very clearly step by step the 'best practices' to create a Typescript npm module.

Nevertheless, great idea and it's very thoroughly tested. Just minor comments about developer experience ;-)

**Comment by Siderite** [comment]
This was actually a Javascript library. I've ported it to TS on a whim. I am starting to doubt it was a good idea. I will read the article and try to improve the experience for TS users. Thanks for the feedback!

**Comment by Siderite** [comment]
The typings have been added in version 1.1.3. Try it out!

**Comment by Siderite** [comment]
I am closing this since typings have been added.

**Comment by Snazzie** [comment]
![image](https://user-images.githubusercontent.com/19627023/76114716-a42ccf80-5fde-11ea-90ad-d8b5182c9340.png)

Typing is not exposed for me
using version 1.2.1

**Comment by Siderite** [comment]
Typings have been added for TS. I don't know how to add it for Node.js. Do you? I will do some research.

**Comment by Siderite** [comment]
OK, I see it works for Node.js as well, but somehow mine are not interpreted correctly. I will investigate. Thanks!

**Comment by Siderite** [comment]
I think it works now for 1.2.2. Try it.
