### ISSUE TITLE
selectMany: the argument must be iterable!

### ISSUE THREAD

**Issue by lennardv2** [Siderite/LInQer#22]
Hi,

I am investigating this library for a project. When testing the selectMany function i stumbled upon the following:

```
Linqer.Enumerable.from([[1,2],[2,3,4]]).selectMany(x => x).toArray();
> [1, 2, 2, 3, 4]
```

Good

```
Linqer.Enumerable.from([{ a: [1,2] }, { a: [2,3,4] }]).selectMany(x => x.a).toArray();
> Error: the argument must be iterable!
```

I was expecting the same result here, but i throws an error. Is this as intended?

Thanks

**Comment by Siderite** [comment]
Nope. It's a bug :) Let me fix it.

**Comment by Siderite** [comment]
Try it now, version 1.2.3.

**Comment by lvoogdt** [comment]
Thanks!
