### ISSUE TITLE
Recommendation to publish on NPM

### ISSUE THREAD

**Issue by Jogai** [Siderite/LInQer#5]
Because it seems awesome :)

**Comment by Siderite** [comment]
Thanks, man! I am not familiar with the NPM publishing style, though. I will look into it. It seems to me that I have to write a separate set of files using ES6 module syntax to be able to use it in NPM and keep the old ones so they can be used in browsers. Do you know of a better way?

**Comment by Jogai** [comment]
Well, I dont know much about publishing either. It seems [simple enough](https://www.freecodecamp.org/news/how-to-make-a-beautiful-tiny-npm-package-and-publish-it-2881d4307f78/) but [there's always more to be said](https://betterstack.dev/blog/npm-package-best-practices/).

**Comment by Siderite** [comment]
Done: https://www.npmjs.com/package/@siderite/linqer

**Comment by REscanDon** [comment]
You should mention the npm right in the readme as it will be the primary way most people will consume the project. Burying it in a linked blog post is not something most visitors will see.

**Comment by Siderite** [comment]
You are right, I've updated the README.
